### ISSUE TITLE
Error raster scan with raster scan map and single beam receiver

### ISSUE THREAD

**Issue by jjpopski** [discos/basie#32]
A raster map gives error if a single beam receiver is selected. On the contrary, when KM receiver is selected, the schedule generation runs smoothly. 
Here below, the configuration of the map, with the target to reproduce the error.Further below, the error traceback.

Configuration of the rastermap:

      EQRASTER = RASTERMAP EQ LAT TR 0.083d 0.083d 60.0 0.01d 0

Target definition:
     ORIA_SB    EQRASTER XK00 EQ  05:35:16h -05:23:14 rvel=0.1 vref=LSRK vdef=OP

`ERROR:basie:Scan EQRASTER on target ORIA_SB
	_get_spacing() takes exactly 3 arguments (1 given)
Traceback (most recent call last):
  File "/usr/local/bin/basie", line 5, in <module>
    basie.cmd_line()
  File "/usr/local/lib/python2.7/dist-packages/basie/__init__.py", line 280, in cmd_line
    _schedule._write_schedule_files()
  File "/usr/local/lib/python2.7/dist-packages/basie/schedule.py", line 239, in _write_schedule_files
    for subscan_id, _subscan in enumerate(_scan.subscans):
  File "/usr/local/lib/python2.7/dist-packages/basie/scan.py", line 53, in subscans
    self.frequency)
  File "/usr/local/lib/python2.7/dist-packages/basie/scanmode/scanmode.py", line 76, in do_scan
    raise ScanError(message)
basie.errors.ScanError: Scan EQRASTER on target ORIA_SB
	_get_spacing() takes exactly 3 arguments (1 given)
`

**Comment by flyingfrog81** [comment]
Opened a new branch issue32 with a proposed fix. It seemed to be a stupid programming error. 
I tried to generate a schedule as defined in the issue description, but please verify that it works correctly before merging the new branch into master.

**Comment by jjpopski** [comment]
:1st_place_medal:    Ero riuscito a identificare l'errore ed itentificare la patch. Stavo per fare push :-)

**Comment by jjpopski** [comment]
issue  32 works correctly.

**Comment by jjpopski** [comment]
fixed in #34 and merged to master
